### ISSUE TITLE
增加通过Spring Security  OAuth2 支持 Google、GitHub 和 Microsoft 等平台进行第三方身份验证的API

### ISSUE THREAD

**Issue by hhyufan** [TwAzuremy/SimpleLogin#1]
### 问题描述
需要实现一个使用 Spring Boot 支持通过 Google、GitHub 和 Microsoft 进行第三方身份验证的 API。该解决方案将利用 Spring Security 的 OAuth2 客户端功能，以简化与这些提供程序的集成。成功通过第三方验证后将自动注册账号，无需绑定平台账号和设置密码，简化了用户注册流程。

#### 1. 核心依赖项
在 `pom.xml` 文件中添加以下依赖项：

```maven
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-oauth2-client</artifactId>
</dependency>
```

#### 2. 提供程序配置（`application.yml`）
在 `application.yml` 文件中配置 OAuth2 客户端信息：

```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: 
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: 
              - user:email
          azure:  # Microsoft 使用 Azure AD
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Azure AD
```

#### 3. 安全配置类
创建一个安全配置类来配置 Spring Security 的 OAuth2 登录：

```java
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.config.annotation.web.builders.WebSecurity;

@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            // 其他代码
            .oauth2Login(oauth2 -> oauth2
                .userInfoEndpoint(userInfo -> userInfo
                    .userService(customOAuth2UserService())
                )
                .successHandler(authenticationSuccessHandler())
            )
    }

    // 自定义用户映射和 JWT 生成的处理程序
    // 实现 OAuth2UserService 和 AuthenticationSuccessHandler
}
```

#### 1. 创建 OAuth 应用程序
为每个提供程序创建 OAuth 应用程序：

- **Google**: 在 [Google Cloud Console](https://console.cloud.google.com/) 中注册应用。
- **GitHub**: 在 [GitHub Developer Settings](https://github.com/settings/developers) 中创建 OAuth 应用。
- **Microsoft**: 在 [Azure AD App Registration](https://portal.azure.com) 中配置应用。

#### 2. 用户映射策略
使用 `registrationId`（提供程序名称）和 `providerUserId`（用户 ID）作为复合键来存储用户。用户在通过第三方验证后，系统将自动注册账号，无需用户进行额外绑定或设置密码。

#### 3. 实现 CustomOAuth2UserService
实现 `CustomOAuth2UserService` 来处理用户的创建和更新，确保将用户信息存储到数据库中。通过此服务，用户的信息将被提取并在数据库中创建新用户记录。

#### 4. JWT 集成
在成功进行 OAuth2 身份验证后生成 JWT 令牌：

- 使用 `AuthenticationSuccessHandler` 接口创建一个处理程序，在用户成功登录后生成 JWT。
- 将 JWT 令牌添加到响应头或 Cookie 中，以便于后续的 API 调用。

### 需要帮助的内容

1. **Azure AD 配置细节**：
   - 确保在 Azure AD 中正确配置重定向 URI。
   - 配置必要的 API 权限，确保应用可以访问用户信息。

2. **处理状态参数以防止 CSRF 攻击**：
   - 在 OAuth2 登录请求中使用状态参数，以验证请求的来源，并增加安全性。

3. **测试多提供程序场景**：
   - 确保能够使用所有提供程序进行测试，验证用户注册和登录的功能。
   - 使用 Postman 或其他工具模拟 OAuth2 流程。

### 参考文档
- [Spring Security OAuth2 文档](https://docs.spring.io/spring-security/site/docs/current/reference/html5/)
- [Google OAuth2 指南](https://developers.google.com/identity/protocols/oauth2)
- [GitHub OAuth 指南](https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app)
- [Microsoft Azure AD 文档](https://docs.microsoft.com/en-us/azure/active-directory/develop/)
